SHOW DATABASES;

USE medicare;
CREATE TABLE medicare(
ID INT(6) NOT NULL AUTO_INCREMENT,
YEAR INT(4), MONTH VARCHAR(10), BENE_GEO_LVL VARCHAR(8), 
BENE_STATE_ABRVTN VARCHAR(2), BENE_STATE_DESC VARCHAR(15), 
BENE_COUNTY_DESC VARCHAR(15), BENE_FIPS_CD INT(5), TOT_BENES INT(8),
ORGNL_MDCR_BENES INT(8), MA_AND_OTH_BENES INT(8), AGED_TOT_BENES INT(8),
AGED_ESRD_BENES INT(8), AGED_NO_ESRD_BENES INT(8), DSBLD_TOT_BENES INT(8),
DSBLD_ESRD_AND_ESRD_ONLY_BENES INT(8),  DSBLD_NO_ESRD_BENES INT(8),
A_B_TOT_BENES INT(8), A_B_MA_AND_OTH_BENES INT(8), PRSCRPTN_DRUG_TOT_BENES INT(8), 
PRSCRPTN_DRUG_PDP_BENES INT(8), PRSCRPTN_DRUG_MAPD_BENES INT(8),
CONSTRAINT medicare_PK PRIMARY KEY(ID)
);

DESC medicare;

# FORGOT TO ENTER A_B_ORGNL_MDCR_BENES COLUMN IN THE TABLE
ALTER TABLE medicare 
ADD COLUMN A_B_ORGNL_MDCR_BENES INT(8) 
AFTER A_B_TOT_BENES;

DESC medicare;
SELECT *
FROM medicare;

SELECT COUNT(*) FROM medicare 
CREATE TABLE MEDICARE2017(
ID INT(6) NOT NULL AUTO_INCREMENT,
YEAR INT(4), MONTH VARCHAR(10), BENE_GEO_LVL VARCHAR(8), 
BENE_STATE_ABRVTN VARCHAR(2), BENE_STATE_DESC VARCHAR(15), 
BENE_COUNTY_DESC VARCHAR(15), BENE_FIPS_CD INT(5), TOT_BENES INT(8),
ORGNL_MDCR_BENES INT(8), MA_AND_OTH_BENES INT(8), AGED_TOT_BENES INT(8),
AGED_ESRD_BENES INT(8), AGED_NO_ESRD_BENES INT(8), DSBLD_TOT_BENES INT(8),
DSBLD_ESRD_AND_ESRD_ONLY_BENES INT(8),  DSBLD_NO_ESRD_BENES INT(8),
A_B_TOT_BENES INT(8), A_B_ORGNL_MDCR_BENES INT(8), A_B_MA_AND_OTH_BENES INT(8), 
PRSCRPTN_DRUG_TOT_BENES INT(8), PRSCRPTN_DRUG_PDP_BENES INT(8), 
PRSCRPTN_DRUG_MAPD_BENES INT(8),
CONSTRAINT medicare_PK PRIMARY KEY(ID)
);

CREATE TABLE MEDICARE2018(
ID INT(6) NOT NULL AUTO_INCREMENT,
YEAR INT(4), MONTH VARCHAR(10), BENE_GEO_LVL VARCHAR(8), 
BENE_STATE_ABRVTN VARCHAR(2), BENE_STATE_DESC VARCHAR(15), 
BENE_COUNTY_DESC VARCHAR(15), BENE_FIPS_CD INT(5), TOT_BENES INT(8),
ORGNL_MDCR_BENES INT(8), MA_AND_OTH_BENES INT(8), AGED_TOT_BENES INT(8),
AGED_ESRD_BENES INT(8), AGED_NO_ESRD_BENES INT(8), DSBLD_TOT_BENES INT(8),
DSBLD_ESRD_AND_ESRD_ONLY_BENES INT(8),  DSBLD_NO_ESRD_BENES INT(8),
A_B_TOT_BENES INT(8), A_B_ORGNL_MDCR_BENES INT(8), A_B_MA_AND_OTH_BENES INT(8), 
PRSCRPTN_DRUG_TOT_BENES INT(8), PRSCRPTN_DRUG_PDP_BENES INT(8), 
PRSCRPTN_DRUG_MAPD_BENES INT(8),
CONSTRAINT medicare_PK PRIMARY KEY(ID)
);

CREATE TABLE MEDICARE2019(
ID INT(6) NOT NULL AUTO_INCREMENT,
YEAR INT(4), MONTH VARCHAR(10), BENE_GEO_LVL VARCHAR(8), 
BENE_STATE_ABRVTN VARCHAR(2), BENE_STATE_DESC VARCHAR(15), 
BENE_COUNTY_DESC VARCHAR(15), BENE_FIPS_CD INT(5), TOT_BENES INT(8),
ORGNL_MDCR_BENES INT(8), MA_AND_OTH_BENES INT(8), AGED_TOT_BENES INT(8),
AGED_ESRD_BENES INT(8), AGED_NO_ESRD_BENES INT(8), DSBLD_TOT_BENES INT(8),
DSBLD_ESRD_AND_ESRD_ONLY_BENES INT(8),  DSBLD_NO_ESRD_BENES INT(8),
A_B_TOT_BENES INT(8), A_B_ORGNL_MDCR_BENES INT(8), A_B_MA_AND_OTH_BENES INT(8), 
PRSCRPTN_DRUG_TOT_BENES INT(8), PRSCRPTN_DRUG_PDP_BENES INT(8), 
PRSCRPTN_DRUG_MAPD_BENES INT(8),
CONSTRAINT medicare_PK PRIMARY KEY(ID)
);

CREATE TABLE MEDICARE2020(
ID INT(6) NOT NULL AUTO_INCREMENT,
YEAR INT(4), MONTH VARCHAR(10), BENE_GEO_LVL VARCHAR(8), 
BENE_STATE_ABRVTN VARCHAR(2), BENE_STATE_DESC VARCHAR(15), 
BENE_COUNTY_DESC VARCHAR(15), BENE_FIPS_CD INT(5), TOT_BENES INT(8),
ORGNL_MDCR_BENES INT(8), MA_AND_OTH_BENES INT(8), AGED_TOT_BENES INT(8),
AGED_ESRD_BENES INT(8), AGED_NO_ESRD_BENES INT(8), DSBLD_TOT_BENES INT(8),
DSBLD_ESRD_AND_ESRD_ONLY_BENES INT(8),  DSBLD_NO_ESRD_BENES INT(8),
A_B_TOT_BENES INT(8), A_B_ORGNL_MDCR_BENES INT(8), A_B_MA_AND_OTH_BENES INT(8), 
PRSCRPTN_DRUG_TOT_BENES INT(8), PRSCRPTN_DRUG_PDP_BENES INT(8), 
PRSCRPTN_DRUG_MAPD_BENES INT(8),
CONSTRAINT medicare_PK PRIMARY KEY(ID)
);

CREATE TABLE MEDICARE2021(
ID INT(6) NOT NULL AUTO_INCREMENT,
YEAR INT(4), MONTH VARCHAR(10), BENE_GEO_LVL VARCHAR(8), 
BENE_STATE_ABRVTN VARCHAR(2), BENE_STATE_DESC VARCHAR(15), 
BENE_COUNTY_DESC VARCHAR(15), BENE_FIPS_CD INT(5), TOT_BENES INT(8),
ORGNL_MDCR_BENES INT(8), MA_AND_OTH_BENES INT(8), AGED_TOT_BENES INT(8),
AGED_ESRD_BENES INT(8), AGED_NO_ESRD_BENES INT(8), DSBLD_TOT_BENES INT(8),
DSBLD_ESRD_AND_ESRD_ONLY_BENES INT(8),  DSBLD_NO_ESRD_BENES INT(8),
A_B_TOT_BENES INT(8), A_B_ORGNL_MDCR_BENES INT(8), A_B_MA_AND_OTH_BENES INT(8), 
PRSCRPTN_DRUG_TOT_BENES INT(8), PRSCRPTN_DRUG_PDP_BENES INT(8), 
PRSCRPTN_DRUG_MAPD_BENES INT(8),
CONSTRAINT medicare_PK PRIMARY KEY(ID)
);

CREATE TABLE MEDICARE2022(
ID INT(6) NOT NULL AUTO_INCREMENT,
YEAR INT(4), MONTH VARCHAR(10), BENE_GEO_LVL VARCHAR(8), 
BENE_STATE_ABRVTN VARCHAR(2), BENE_STATE_DESC VARCHAR(15), 
BENE_COUNTY_DESC VARCHAR(15), BENE_FIPS_CD INT(5), TOT_BENES INT(8),
ORGNL_MDCR_BENES INT(8), MA_AND_OTH_BENES INT(8), AGED_TOT_BENES INT(8),
AGED_ESRD_BENES INT(8), AGED_NO_ESRD_BENES INT(8), DSBLD_TOT_BENES INT(8),
DSBLD_ESRD_AND_ESRD_ONLY_BENES INT(8),  DSBLD_NO_ESRD_BENES INT(8),
A_B_TOT_BENES INT(8), A_B_ORGNL_MDCR_BENES INT(8), A_B_MA_AND_OTH_BENES INT(8), 
PRSCRPTN_DRUG_TOT_BENES INT(8), PRSCRPTN_DRUG_PDP_BENES INT(8), 
PRSCRPTN_DRUG_MAPD_BENES INT(8),
CONSTRAINT medicare_PK PRIMARY KEY(ID)
);

SHOW DATABASES;
USE medicare;
SHOW TABLE STATUS;

DESC medicare2017;
SELECT *
FROM medicare2017;

SELECT COUNT(*) FROM medicare2017 

SELECT *
FROM medicare2018;
SELECT COUNT(*) FROM medicare2018

DROP TABLE medicare;
SHOW TABLE STATUS;

SELECT *
FROM medicare2019;
SELECT COUNT(*) FROM medicare2019

SELECT *
FROM medicare2020;
SELECT COUNT(*) FROM medicare2020

SELECT *
FROM medicare2021;
SELECT COUNT(*) FROM medicare2021

SELECT * FROM information_schema.medicare2022 
WHERE table_schema =  'medicare2022' 
ORDER BY medicare2022;
